// Package openapi Code generated by swaggo/swag. DO NOT EDIT
package openapi

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/auth/register": {
            "post": {
                "description": "使用用户名密码进行注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.HttpResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/http.HttpResponse"
                        }
                    }
                }
            }
        },
        "/admin/user": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "分页获取后台用户列表，支持按角色与关键字筛选（keyword 可匹配 uid/username/email）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AdminUser"
                ],
                "summary": "管理员-用户列表",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "角色",
                        "name": "role",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键字(uid/username/email)",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.HttpResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建后台用户（密码会在服务层进行 bcrypt 加密）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AdminUser"
                ],
                "summary": "管理员-创建用户",
                "parameters": [
                    {
                        "description": "创建用户请求",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.CreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.HttpResponse"
                        }
                    }
                }
            }
        },
        "/admin/user/{uid}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "按 UID 更新后台用户（邮箱/角色/启用状态）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AdminUser"
                ],
                "summary": "管理员-更新用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 UID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新用户请求",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.HttpResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "按 UID 删除后台用户（建议实现为软删除：is_deleted=true）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AdminUser"
                ],
                "summary": "管理员-删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 UID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.HttpResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LoginReq": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "http.Code": {
            "type": "integer",
            "enum": [
                200,
                400,
                422,
                401,
                403,
                404,
                409,
                409,
                500,
                501,
                401,
                401,
                500
            ],
            "x-enum-comments": {
                "AlreadyExists": "资源已存在（唯一键冲突等，与 Conflict 同值）",
                "Conflict": "资源冲突（状态冲突/并发更新冲突等）",
                "Forbidden": "已登录但无权限",
                "InternalError": "服务内部错误（兜底）",
                "InvalidParam": "参数错误（解析/缺失/类型不符）",
                "NotFound": "资源不存在",
                "NotImplemented": "功能未实现",
                "Unauthorized": "未登录/缺少 token/鉴权失败",
                "ValidationFail": "参数校验失败（binding/validator）"
            },
            "x-enum-descriptions": [
                "",
                "参数错误（解析/缺失/类型不符）",
                "参数校验失败（binding/validator）",
                "未登录/缺少 token/鉴权失败",
                "已登录但无权限",
                "资源不存在",
                "资源冲突（状态冲突/并发更新冲突等）",
                "资源已存在（唯一键冲突等，与 Conflict 同值）",
                "服务内部错误（兜底）",
                "功能未实现",
                "",
                "",
                ""
            ],
            "x-enum-varnames": [
                "Success",
                "InvalidParam",
                "ValidationFail",
                "Unauthorized",
                "Forbidden",
                "NotFound",
                "Conflict",
                "AlreadyExists",
                "InternalError",
                "NotImplemented",
                "TokenExpired",
                "TokenInvalid",
                "Failed"
            ]
        },
        "http.HttpPageResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "allOf": [
                        {
                            "$ref": "#/definitions/http.Code"
                        }
                    ]
                },
                "data": {
                    "description": "响应数据(可以为空)"
                },
                "message": {
                    "description": "响应描述",
                    "type": "string"
                },
                "page": {
                    "description": "响应分页页码",
                    "type": "integer"
                },
                "size": {
                    "description": "响应分页大小",
                    "type": "integer"
                },
                "total": {
                    "description": "响应分页总条数",
                    "type": "integer"
                }
            }
        },
        "http.HttpResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "allOf": [
                        {
                            "$ref": "#/definitions/http.Code"
                        }
                    ]
                },
                "data": {
                    "description": "响应数据(可以为空)"
                },
                "message": {
                    "description": "响应描述",
                    "type": "string"
                }
            }
        },
        "user.CreateReq": {
            "type": "object",
            "required": [
                "password",
                "role",
                "username"
            ],
            "properties": {
                "email": {
                    "description": "选填，但如果有值必须符合邮箱格式",
                    "type": "string"
                },
                "password": {
                    "description": "必填，创建时传入明文密码",
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 6
                },
                "role": {
                    "description": "角色：不要写死 oneof，使用 user.Role(req.Role).IsValid() 统一校验（在 handler/service 层做）",
                    "type": "string"
                },
                "username": {
                    "description": "必填，且通常有长度限制",
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 3
                }
            }
        },
        "user.UpdateReq": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "允许修改邮箱",
                    "type": "string"
                },
                "is_active": {
                    "description": "使用指针，以便区分 \"不修改\" 和 \"修改为禁用(false)\"",
                    "type": "boolean"
                },
                "role": {
                    "description": "允许修改角色：不要写死 oneof，使用 user.Role(req.Role).IsValid() 统一校验（在 handler/service 层做）",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Mall API",
	Description:      "Mall API 服务接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
