// Package openapi Code generated by swaggo/swag. DO NOT EDIT
package openapi

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/auth/login": {
            "post": {
                "description": "用户名/密码登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "用户登录",
                "operationId": "login",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.loginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "$ref": "#/definitions/http.HttpResponse-auth_loginRes"
                        }
                    }
                }
            }
        },
        "/admin/auth/register": {
            "post": {
                "description": "用户名/密码进行注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "用户注册",
                "operationId": "register",
                "parameters": [
                    {
                        "description": "注册参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.registerReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册成功",
                        "schema": {
                            "$ref": "#/definitions/http.HttpResponse-Empty"
                        }
                    }
                }
            }
        },
        "/admin/auth/session/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "用户注销,同时移除刷新令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "用户注销",
                "operationId": "logout",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式: refresh_token=xxx",
                        "name": "Cookie",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注销成功",
                        "schema": {
                            "$ref": "#/definitions/http.HttpResponse-Empty"
                        }
                    }
                }
            }
        },
        "/admin/auth/session/refresh": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "用于短期令牌 Access_Token 续期",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "刷新令牌",
                "operationId": "refreshToken",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式: refresh_token=xxx",
                        "name": "Cookie",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "刷新成功",
                        "schema": {
                            "$ref": "#/definitions/http.HttpResponse-auth_loginRes"
                        }
                    }
                }
            }
        },
        "/admin/user": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "支持分页以及条件查询",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "获取用户列表",
                "operationId": "listUser",
                "parameters": [
                    {
                        "type": "string",
                        "description": "关键字：多字段综合搜索， email/username/uid",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "example": 1,
                        "description": "当前页码，默认 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "角色：枚举",
                        "name": "role",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "example": 10,
                        "description": "每页数量，默认 10，最大 100",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功",
                        "schema": {
                            "$ref": "#/definitions/http.HttpResponse-http_PageRes-user_listRes"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.loginReq": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string",
                    "example": "123456"
                },
                "username": {
                    "description": "用户名",
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "auth.loginRes": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "访问令牌: 15分钟过期",
                    "type": "string"
                },
                "expires_at": {
                    "description": "过期时间：访问令牌 Access_token 过期时间(秒)",
                    "type": "integer"
                },
                "uid": {
                    "description": "用户UID",
                    "type": "string"
                }
            }
        },
        "auth.registerReq": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string",
                    "example": "123456"
                },
                "username": {
                    "description": "用户名",
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "http.Empty": {
            "type": "object"
        },
        "http.HttpResponse-Empty": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "code: HTTP 状态码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "data: 响应数据（可以为空）",
                    "allOf": [
                        {
                            "$ref": "#/definitions/http.Empty"
                        }
                    ]
                },
                "message": {
                    "description": "message: 响应描述",
                    "type": "string",
                    "example": "操作成功"
                }
            }
        },
        "http.HttpResponse-auth_loginRes": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "code: HTTP 状态码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "data: 响应数据（可以为空）",
                    "allOf": [
                        {
                            "$ref": "#/definitions/auth.loginRes"
                        }
                    ]
                },
                "message": {
                    "description": "message: 响应描述",
                    "type": "string",
                    "example": "操作成功"
                }
            }
        },
        "http.HttpResponse-http_PageRes-user_listRes": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "code: HTTP 状态码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "data: 响应数据（可以为空）",
                    "allOf": [
                        {
                            "$ref": "#/definitions/http.PageRes-user_listRes"
                        }
                    ]
                },
                "message": {
                    "description": "message: 响应描述",
                    "type": "string",
                    "example": "操作成功"
                }
            }
        },
        "http.PageRes-user_listRes": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.listRes"
                    }
                },
                "page": {
                    "description": "当前页码",
                    "type": "integer",
                    "example": 1
                },
                "size": {
                    "description": "分页大小",
                    "type": "integer",
                    "example": 10
                },
                "total": {
                    "description": "总数",
                    "type": "integer",
                    "example": 50
                }
            }
        },
        "user.listRes": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "* 创建时间 (JSON会自动格式化为 RFC3339 字符串)",
                    "type": "string"
                },
                "email": {
                    "description": "* 邮箱",
                    "type": "string"
                },
                "id": {
                    "description": "* ID (对应数据库的 UID) - 前端通常习惯叫 id",
                    "type": "string"
                },
                "is_active": {
                    "description": "* 账号状态",
                    "type": "boolean"
                },
                "role": {
                    "description": "* 角色标识",
                    "type": "string"
                },
                "updated_at": {
                    "description": "* 更新时间",
                    "type": "string"
                },
                "username": {
                    "description": "* 登录用户名",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "输入格式: Bearer \u003ctoken\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "CookieAuth": {
            "description": "浏览器自动处理。手动调试请填写：refresh_token=xxxx",
            "type": "apiKey",
            "name": "Cookie",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Mall API",
	Description:      "Mall API 服务接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
