/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Mall API
 * Mall API 服务接口文档
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  HttpHttpResponseAuthLoginRes,
  HttpHttpResponseEmpty
} from '.././model';


export const getLoginResponseMock = (overrideResponse: Partial< HttpHttpResponseAuthLoginRes > = {}): HttpHttpResponseAuthLoginRes => ({code: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), data: faker.helpers.arrayElement([{...{access_token: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), expires_at: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), refresh_token: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), uid: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])},}, undefined]), message: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getLogoutResponseMock = (overrideResponse: Partial< HttpHttpResponseEmpty > = {}): HttpHttpResponseEmpty => ({code: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), data: faker.helpers.arrayElement([{}, undefined]), message: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getRefreshTokenResponseMock = (overrideResponse: Partial< HttpHttpResponseAuthLoginRes > = {}): HttpHttpResponseAuthLoginRes => ({code: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), data: faker.helpers.arrayElement([{...{access_token: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), expires_at: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), refresh_token: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), uid: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])},}, undefined]), message: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getRegisterResponseMock = (overrideResponse: Partial< HttpHttpResponseEmpty > = {}): HttpHttpResponseEmpty => ({code: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), data: faker.helpers.arrayElement([{}, undefined]), message: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})


export const getLoginMockHandler = (overrideResponse?: HttpHttpResponseAuthLoginRes | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<HttpHttpResponseAuthLoginRes> | HttpHttpResponseAuthLoginRes), options?: RequestHandlerOptions) => {
  return http.post('*/admin/auth/login', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getLoginResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getLogoutMockHandler = (overrideResponse?: HttpHttpResponseEmpty | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<HttpHttpResponseEmpty> | HttpHttpResponseEmpty), options?: RequestHandlerOptions) => {
  return http.post('*/admin/auth/logout', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getLogoutResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getRefreshTokenMockHandler = (overrideResponse?: HttpHttpResponseAuthLoginRes | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<HttpHttpResponseAuthLoginRes> | HttpHttpResponseAuthLoginRes), options?: RequestHandlerOptions) => {
  return http.post('*/admin/auth/refresh', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getRefreshTokenResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getRegisterMockHandler = (overrideResponse?: HttpHttpResponseEmpty | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<HttpHttpResponseEmpty> | HttpHttpResponseEmpty), options?: RequestHandlerOptions) => {
  return http.post('*/admin/auth/register', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getRegisterResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getAuthMock = () => [
  getLoginMockHandler(),
  getLogoutMockHandler(),
  getRefreshTokenMockHandler(),
  getRegisterMockHandler()
]
