/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Mall API
 * Mall API 服务接口文档
 * OpenAPI spec version: 1.0
 */

import type { MutationFunction, QueryClient, UseMutationOptions, UseMutationResult } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";
import type { BodyType, ErrorType } from "../../core/http-client";

import { httpClient } from "../../core/http-client";
import { refreshClient } from "../../core/refresh-client";
import type { AuthLoginReq, AuthRegisterReq, HttpHttpResponseAuthLoginRes, HttpHttpResponseEmpty } from ".././model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 用户名/密码登录
 * @summary 用户登录
 */
export const login = (authLoginReq: BodyType<AuthLoginReq>, options?: SecondParameter<typeof httpClient>, signal?: AbortSignal) => {
	return httpClient<HttpHttpResponseAuthLoginRes>(
		{ url: `/admin/auth/login`, method: "POST", headers: { "Content-Type": "application/json" }, data: authLoginReq, signal },
		options,
	);
};

export const getLoginMutationOptions = <TError = ErrorType<unknown>, TContext = unknown>(options?: {
	mutation?: UseMutationOptions<Awaited<ReturnType<typeof login>>, TError, { data: BodyType<AuthLoginReq> }, TContext>;
	request?: SecondParameter<typeof httpClient>;
}): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError, { data: BodyType<AuthLoginReq> }, TContext> => {
	const mutationKey = ["login"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, { data: BodyType<AuthLoginReq> }> = (props) => {
		const { data } = props ?? {};

		return login(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>;
export type LoginMutationBody = BodyType<AuthLoginReq>;
export type LoginMutationError = ErrorType<unknown>;

/**
 * @summary 用户登录
 */
export const useLogin = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof login>>, TError, { data: BodyType<AuthLoginReq> }, TContext>;
		request?: SecondParameter<typeof httpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof login>>, TError, { data: BodyType<AuthLoginReq> }, TContext> => {
	const mutationOptions = getLoginMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * 用户名/密码进行注册
 * @summary 用户注册
 */
export const register = (authRegisterReq: BodyType<AuthRegisterReq>, options?: SecondParameter<typeof httpClient>, signal?: AbortSignal) => {
	return httpClient<HttpHttpResponseEmpty>(
		{ url: `/admin/auth/register`, method: "POST", headers: { "Content-Type": "application/json" }, data: authRegisterReq, signal },
		options,
	);
};

export const getRegisterMutationOptions = <TError = ErrorType<unknown>, TContext = unknown>(options?: {
	mutation?: UseMutationOptions<Awaited<ReturnType<typeof register>>, TError, { data: BodyType<AuthRegisterReq> }, TContext>;
	request?: SecondParameter<typeof httpClient>;
}): UseMutationOptions<Awaited<ReturnType<typeof register>>, TError, { data: BodyType<AuthRegisterReq> }, TContext> => {
	const mutationKey = ["register"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof register>>, { data: BodyType<AuthRegisterReq> }> = (props) => {
		const { data } = props ?? {};

		return register(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>;
export type RegisterMutationBody = BodyType<AuthRegisterReq>;
export type RegisterMutationError = ErrorType<unknown>;

/**
 * @summary 用户注册
 */
export const useRegister = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof register>>, TError, { data: BodyType<AuthRegisterReq> }, TContext>;
		request?: SecondParameter<typeof httpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof register>>, TError, { data: BodyType<AuthRegisterReq> }, TContext> => {
	const mutationOptions = getRegisterMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * 用户注销,同时移除刷新令牌
 * @summary 用户注销
 */
export const logout = (options?: SecondParameter<typeof httpClient>, signal?: AbortSignal) => {
	return httpClient<HttpHttpResponseEmpty>({ url: `/admin/auth/session/logout`, method: "POST", signal }, options);
};

export const getLogoutMutationOptions = <TError = ErrorType<unknown>, TContext = unknown>(options?: {
	mutation?: UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError, void, TContext>;
	request?: SecondParameter<typeof httpClient>;
}): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError, void, TContext> => {
	const mutationKey = ["logout"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, void> = () => {
		return logout(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>;

export type LogoutMutationError = ErrorType<unknown>;

/**
 * @summary 用户注销
 */
export const useLogout = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError, void, TContext>;
		request?: SecondParameter<typeof httpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof logout>>, TError, void, TContext> => {
	const mutationOptions = getLogoutMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * 用于短期令牌 Access_Token 续期
 * @summary 刷新令牌
 */
export const refreshToken = (options?: SecondParameter<typeof refreshClient>, signal?: AbortSignal) => {
	return refreshClient<HttpHttpResponseAuthLoginRes>({ url: `/admin/auth/session/refresh`, method: "POST", signal }, options);
};

export const getRefreshTokenMutationOptions = <TError = unknown, TContext = unknown>(options?: {
	mutation?: UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError, void, TContext>;
	request?: SecondParameter<typeof refreshClient>;
}): UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError, void, TContext> => {
	const mutationKey = ["refreshToken"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof refreshToken>>, void> = () => {
		return refreshToken(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type RefreshTokenMutationResult = NonNullable<Awaited<ReturnType<typeof refreshToken>>>;

export type RefreshTokenMutationError = unknown;

/**
 * @summary 刷新令牌
 */
export const useRefreshToken = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError, void, TContext>;
		request?: SecondParameter<typeof refreshClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof refreshToken>>, TError, void, TContext> => {
	const mutationOptions = getRefreshTokenMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
