/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Mall API
 * Mall API 服务接口文档
 * OpenAPI spec version: 1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useQuery } from "@tanstack/react-query";
import type { ErrorType } from "../../core/http-client";

import { httpClient } from "../../core/http-client";
import type { HttpHttpResponseHttpPageResUserListRes, ListUserParams } from ".././model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 支持分页以及条件查询
 * @summary 获取用户列表
 */
export const listUser = (params?: ListUserParams, options?: SecondParameter<typeof httpClient>, signal?: AbortSignal) => {
	return httpClient<HttpHttpResponseHttpPageResUserListRes>({ url: `/admin/user`, method: "GET", params, signal }, options);
};

export const getListUserQueryKey = (params?: ListUserParams) => {
	return [`/admin/user`, ...(params ? [params] : [])] as const;
};

export const getListUserQueryOptions = <TData = Awaited<ReturnType<typeof listUser>>, TError = ErrorType<unknown>>(
	params?: ListUserParams,
	options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listUser>>, TError, TData>>; request?: SecondParameter<typeof httpClient> },
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getListUserQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof listUser>>> = ({ signal }) => listUser(params, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof listUser>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type ListUserQueryResult = NonNullable<Awaited<ReturnType<typeof listUser>>>;
export type ListUserQueryError = ErrorType<unknown>;

export function useListUser<TData = Awaited<ReturnType<typeof listUser>>, TError = ErrorType<unknown>>(
	params: undefined | ListUserParams,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listUser>>, TError, TData>> &
			Pick<DefinedInitialDataOptions<Awaited<ReturnType<typeof listUser>>, TError, Awaited<ReturnType<typeof listUser>>>, "initialData">;
		request?: SecondParameter<typeof httpClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListUser<TData = Awaited<ReturnType<typeof listUser>>, TError = ErrorType<unknown>>(
	params?: ListUserParams,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listUser>>, TError, TData>> &
			Pick<UndefinedInitialDataOptions<Awaited<ReturnType<typeof listUser>>, TError, Awaited<ReturnType<typeof listUser>>>, "initialData">;
		request?: SecondParameter<typeof httpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListUser<TData = Awaited<ReturnType<typeof listUser>>, TError = ErrorType<unknown>>(
	params?: ListUserParams,
	options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listUser>>, TError, TData>>; request?: SecondParameter<typeof httpClient> },
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 获取用户列表
 */

export function useListUser<TData = Awaited<ReturnType<typeof listUser>>, TError = ErrorType<unknown>>(
	params?: ListUserParams,
	options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listUser>>, TError, TData>>; request?: SecondParameter<typeof httpClient> },
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getListUserQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}
