// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gin-gonic/gin"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
	"mall-api/internal/app/admin/wire"
	"mall-api/internal/database"
	"mall-api/internal/router"
)

// Injectors from wire.go:

// InitApp builds the full application graph: DB, Redis, Gin Engine, module handlers,
// and routes registration.
//
// This injector lets you remove manual DB/Redis/router wiring from cmd/server.
func InitApp() (*App, error) {
	engine := provideGinEngine()
	db, err := database.InitDB()
	if err != nil {
		return nil, err
	}
	client, err := database.InitRedis()
	if err != nil {
		return nil, err
	}
	adminHandlers, err := provideAdminHandlers(db, client)
	if err != nil {
		return nil, err
	}
	wireRoutersRegistered := provideRouters(engine, db, client)
	app := &App{
		Engine:            engine,
		DB:                db,
		RDB:               client,
		AdminHandlers:     adminHandlers,
		RoutersRegistered: wireRoutersRegistered,
	}
	return app, nil
}

// wire.go:

// App is the fully-wired application object returned by the injector.
type App struct {
	Engine *gin.Engine
	DB     *gorm.DB
	RDB    *redis.Client

	// Keep these as fields so Wire considers the providers "used" and also so
	// the application graph guarantees these side-effects happen during init.
	AdminHandlers     *wire.AdminHandlers
	RoutersRegistered routersRegistered
}

// routersRegistered is a no-op marker type used to model "route registration happened"
// as a Wire-provided dependency.
type routersRegistered struct{}

// provideGinEngine constructs a bare gin engine. Middlewares are configured in main
// in this repo; if you want to move middleware wiring into Wire, do it here.
func provideGinEngine() *gin.Engine {
	return gin.New()
}

// provideAdminHandlers wires up admin module handlers (auth/user/etc).
func provideAdminHandlers(db *gorm.DB, rdb *redis.Client) (*wire.AdminHandlers, error) {
	return wire.InitAdminHandlers(db, rdb)
}

// provideRouters registers routes onto gin.Engine (side-effect) and returns a marker.
// Wire providers must return at least one output, so we return a no-op type here.
func provideRouters(r *gin.Engine, db *gorm.DB, rdb *redis.Client) routersRegistered {
	router.Router(r, db, rdb)
	return routersRegistered{}
}
