/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Mall API
 * Mall API 服务接口文档
 * OpenAPI spec version: 1.0
 */

export interface AuthLoginReq {
  /** 密码 */
  password: string;
  /** 用户名 */
  username: string;
}
