/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Mall API
 * Mall API 服务接口文档
 * OpenAPI spec version: 1.0
 */

export interface AuthLoginRes {
	/** 访问令牌: 15分钟过期 */
	access_token?: string;
	/** 过期时间：访问令牌 Access_token 过期时间(秒) */
	expires_at?: number;
	/** 用户UID */
	uid?: string;
}
