/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Mall API
 * Mall API 服务接口文档
 * OpenAPI spec version: 1.0
 */
import type { UserListRes } from "./userListRes";

export interface HttpPageResUserListRes {
	/** 列表 */
	list?: UserListRes[];
	/** 当前页码 */
	page?: number;
	/** 分页大小 */
	size?: number;
	/** 总数 */
	total?: number;
}
