/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Mall API
 * Mall API 服务接口文档
 * OpenAPI spec version: 1.0
 */

export type ListUserParams = {
	/**
	 * 关键字：多字段综合搜索， email/username/uid
	 */
	keyword?: string;
	/**
	 * 当前页码，默认 1
	 * @minimum 1
	 */
	page?: number;
	/**
	 * 角色：枚举
	 */
	role?: string;
	/**
	 * 每页数量，默认 10，最大 100
	 * @minimum 1
	 * @maximum 100
	 */
	size?: number;
};
