/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Mall API
 * Mall API 服务接口文档
 * OpenAPI spec version: 1.0
 */

export interface UserListRes {
	/** * 创建时间 (JSON会自动格式化为 RFC3339 字符串) */
	created_at?: string;
	/** * 邮箱 */
	email?: string;
	/** * ID (对应数据库的 UID) - 前端通常习惯叫 id */
	id?: string;
	/** * 账号状态 */
	is_active?: boolean;
	/** * 角色标识 */
	role?: string;
	/** * 更新时间 */
	updated_at?: string;
	/** * 登录用户名 */
	username?: string;
}
